In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('amazon.csv')

In [3]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [4]:
df.shape

(1465, 16)

In [5]:
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 183.3 KB

In [7]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
print("Unique Products:", df['product_id'].nunique())
print("Unique Users:", df['user_id'].nunique())
print("Unique Categories:", df['category'].nunique())

Unique Products: 1351
Unique Users: 1194
Unique Categories: 211

In [10]:
df.dropna(subset=['rating_count'], inplace=True)

In [11]:
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           0
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [12]:
df['rating'].value_counts()

rating
4.1    244
4.3    230
4.2    228
4.0    129
3.9    123
4.4    123
3.8     86
4.5     75
4       52
3.7     42
3.6     35
3.5     26
4.6     17
3.3     16
3.4     10
4.7      6
3.1      4
4.8      3
3.2      2
5.0      2
3.0      2
2.8      2
2.3      1
|        1
2        1
3        1
2.6      1
2.9      1
Name: count, dtype: int64

In [13]:
df['category'].value_counts().head(10)

category
Computers&Accessories|Accessories&Peripherals|Cables&Accessories|Cables|USBCables                        231
Electronics|WearableTechnology|SmartWatches                                                               76
Electronics|Mobiles&Accessories|Smartphones&BasicMobiles|Smartphones                                      68
Electronics|HomeTheater,TV&Video|Televisions|SmartTelevisions                                             63
Electronics|Headphones,Earbuds&Accessories|Headphones|In-Ear                                              52
Electronics|HomeTheater,TV&Video|Accessories|RemoteControls                                               49
Home&Kitchen|Kitchen&HomeAppliances|SmallKitchenAppliances|MixerGrinders                                  27
Electronics|HomeTheater,TV&Video|Accessories|Cables|HDMICables                                            24
Computers&Accessories|Accessories&Peripherals|Keyboards,Mice&InputDevices|Mice                            24
Home&Kitchen|Kitchen&HomeAppliances|Vacuum,Cleaning&Ironing|Irons,Steamers&Accessories|Irons|DryIrons     24
Name: count, dtype: int64

In [14]:
df = df[pd.to_numeric(df['rating'], errors='coerce').notnull()]
df['rating'] = df['rating'].astype(float)

In [15]:
df['rating'].dtype

dtype('float64')

In [16]:
df['combined_features'] = df['product_name'] + ' ' + df['category'] + ' ' + df['about_product']

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['combined_features'])

In [20]:
tfidf_matrix.shape

(1462, 10358)

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [23]:
cosine_sim.shape

(1462, 1462)

In [24]:
indices = pd.Series(df.index, index=df['product_name']).drop_duplicates()

In [27]:
def recommend_products(product_name, top_n=5):
    idx = indices[product_name]

    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]
    product_indices = [i[0] for i in sim_scores]

    return df['product_name'].iloc[product_indices]

In [31]:
recommend_products(df['product_name'].iloc[123])

292    Hisense 126 cm (50 inches) Bezelless Series 4K...
323    TCL 108 cm (43 inches) 4K Ultra HD Certified A...
94     TCL 100 cm (40 inches) Full HD Certified Andro...
61     Samsung 108 cm (43 inches) Crystal 4K Neo Seri...
280    Toshiba 108 cm (43 inches) V Series Full HD Sm...
Name: product_name, dtype: str

# Content-Based Recommendation System

## Overview
Content-Based Recommendation System recommends products based on the features of the products themselves. It analyzes product information such as product name, category, and description, and recommends items that are similar to the one selected by the user.

In this project, we use:
- **Product Name**
- **Category**
- **About Product**

to create a combined feature set for each product.

---

## Steps Performed

### 1. Feature Combination
The important product-related columns were merged into a single column named `combined_features`.

Purpose:
To create a complete textual representation of each product.

---

### 2. TF-IDF Vectorization
TF-IDF (Term Frequency - Inverse Document Frequency) was applied on the combined features.

Purpose:
To convert text data into numerical vectors so that the machine can process and compare products.

---

### 3. Cosine Similarity Calculation
Cosine similarity was calculated between all products.

Purpose:
To measure how similar one product is to another.

Range:
- **0** → Completely different
- **1** → Exactly similar

---

### 4. Recommendation Function
A function was created to:
- Take a product name as input
- Find its similarity with all products
- Return the top 5 most similar products

---

## Result
The model successfully recommends similar products.

Example:
If the input product is a **Television**, the output also recommends other televisions from similar brands and categories.

This shows that the content-based recommendation system is working correctly.

In [32]:
user_item_matrix = df.pivot_table(index='user_id', columns='product_id', values='rating')

In [33]:
user_item_matrix.head()

product_id,B002PD61Y4,B002SZEOLG,B003B00484,B003L62T7W,B004IO5BMQ,B005FYNT3G,B005LJQMCK,B005LJQMZC,B006LW0WDQ,B0073QGKAS,...,B0BNXFDTZ2,B0BP18W8TM,B0BP7XLX48,B0BP89YBC1,B0BPBG712X,B0BPBXNQQT,B0BPCJM7TB,B0BPJBTB3F,B0BQ3K23Y1,B0BR4F878Q
user_id,,,,,,,,,,,,,,,,,,,,,
"AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZAHJK6NGYHFMA,AGYURQ3476BNT4D2O46THXEUY3SA,AFPMBSBIEX45OQ6UCQWPDG55GWLQ,AGWJU3WUQBDQYPSYAJSR3AKBLCOA,AEOVUNFCIFV223O536GVW5JHZKOA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE23RS3W7GZO7LHYKJU6KSKVM4MQ,AEQUNEY6GQOTEGUMS6KRUEYNXJSQ,AGYPIE5BICV44WEEEPJVEFQOCJSQ,AFR7CEQKWZE53IHHOWBIPAMYKL4Q,AGBV7FBP4SEITF6UKRFKTV7O32IA,AHQVOY54QKPIQZIJ57JKCGQPVV3Q,AEMCVRRD3XQRGFHC2VFCXHJEMESQ,AFBWXU7DUWCIK5MRDCLBXWTWN7ZQ",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AE242TR3GQ6TYC6W4SJ5UYYKBTYQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE27UOZENYSWCQVQRRUQIV2ZM7VA,AGMYSLV6NNOAYES25JDTJPCZY47A,AFHS33MWRQGSS64EETZJGCBWXXXA,AHYXZVXUY3QTBP7IBFIUBSZVH2XQ,AH2SHWYEWDAK6A5Y2ZBEMZ2KIG3A,AEYMOGP2CYRKYZ7TIDNLGR5QPZ4Q,AGPGDCCXPI3EACMNJKBCNT57DVFA,AFPBMRYRSMD3PP3CBKLFF7EKOCXA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE2JTMRKTUOIVIZWS2WDGTMNTU4Q,AF4QXCB32VC2DVE7O3DGFNQVFFNQ,AGAFYHMPFGVPR3MOS4QAZLAWPW3A,AGNNWLEF6V57TKIFJM7SWHNFAIQQ,AFVIPOPKMOCVCX3CMXUJHMWDIMGA,AH6MFUU725GG4KA3XTALSTU2ILHA,AGQYTSKE2UBYARZYRBADQMX6BJPQ,AG7F66F724JZ2HIJQY7NOU5M5D2Q",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
user_item_matrix.shape

(1191, 1348)

In [35]:
user_item_matrix.notnull().sum().sum()

np.int64(1358)

In [36]:
user_item_matrix.stack().head(10)

user_id                                                                                                                                                                        product_id
AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZAHJK6NGYHFMA,AGYURQ3476BNT4D2O46THXEUY3SA,AFPMBSBIEX45OQ6UCQWPDG55GWLQ,AGWJU3WUQBDQYPSYAJSR3AKBLCOA,AEOVUNFCIFV223O536GVW5JHZKOA  B002PD61Y4   NaN
                                                                                                                                                                               B002SZEOLG   NaN
                                                                                                                                                                               B003B00484   NaN
                                                                                                                                                                               B003L62T7W   NaN
                                                                                                                                                                               B004IO5BMQ   NaN
                                                                                                                                                                               B005FYNT3G   NaN
                                                                                                                                                                               B005LJQMCK   NaN
                                                                                                                                                                               B005LJQMZC   NaN
                                                                                                                                                                               B006LW0WDQ   NaN
                                                                                                                                                                               B0073QGKAS   NaN
dtype: float64

In [37]:
user_item_matrix.stack().reset_index().head(10)

                                             user_id  product_id   0
0  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B002PD61Y4 NaN
1  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B002SZEOLG NaN
2  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B003B00484 NaN
3  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B003L62T7W NaN
4  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B004IO5BMQ NaN
5  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B005FYNT3G NaN
6  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B005LJQMCK NaN
7  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B005LJQMZC NaN
8  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B006LW0WDQ NaN
9  AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZA...  B0073QGKAS NaN

In [38]:
df['rating'].dtype

dtype('float64')

In [39]:
df[['user_id','product_id','rating']].head(10)

                                             user_id  product_id  rating
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...  B07JW9H4J1     4.2
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...  B098NS6PVG     4.0
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...  B096MSW6CT     3.9
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...  B08HDJ86NZ     4.2
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...  B08CF3B7N1     4.2
5  AEQ2YMXSZWEOHK2EHTNLOS56YTZQ,AGRVINWECNY7323CW...  B08Y1TFSP6     3.9
6  AG7C6DAADCTRQJG2BRS3RIKDT52Q,AFU7BOMPVJ7Q3TTA4...  B08WRWPM22     4.1
7  AHW6E5LQ2BDYOIVLAJGDH45J5V5Q,AF74RSGCHPZITVFSZ...  B08DDRGWTJ     4.3
8  AGV3IEFANZCKECFGUM42MRH5FNOA,AEBO7NWCNXKT4AESA...  B008IFXQFU     4.2
9  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...  B082LZGK39     4.0

In [40]:
df[['user_id','product_id','rating']].isnull().sum()

user_id       0
product_id    0
rating        0
dtype: int64

In [41]:
user_item_matrix.iloc[:10, :10]

product_id,B002PD61Y4,B002SZEOLG,B003B00484,B003L62T7W,B004IO5BMQ,B005FYNT3G,B005LJQMCK,B005LJQMZC,B006LW0WDQ,B0073QGKAS
user_id,,,,,,,,,,
"AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZAHJK6NGYHFMA,AGYURQ3476BNT4D2O46THXEUY3SA,AFPMBSBIEX45OQ6UCQWPDG55GWLQ,AGWJU3WUQBDQYPSYAJSR3AKBLCOA,AEOVUNFCIFV223O536GVW5JHZKOA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE23RS3W7GZO7LHYKJU6KSKVM4MQ,AEQUNEY6GQOTEGUMS6KRUEYNXJSQ,AGYPIE5BICV44WEEEPJVEFQOCJSQ,AFR7CEQKWZE53IHHOWBIPAMYKL4Q,AGBV7FBP4SEITF6UKRFKTV7O32IA,AHQVOY54QKPIQZIJ57JKCGQPVV3Q,AEMCVRRD3XQRGFHC2VFCXHJEMESQ,AFBWXU7DUWCIK5MRDCLBXWTWN7ZQ",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AE242TR3GQ6TYC6W4SJ5UYYKBTYQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE27UOZENYSWCQVQRRUQIV2ZM7VA,AGMYSLV6NNOAYES25JDTJPCZY47A,AFHS33MWRQGSS64EETZJGCBWXXXA,AHYXZVXUY3QTBP7IBFIUBSZVH2XQ,AH2SHWYEWDAK6A5Y2ZBEMZ2KIG3A,AEYMOGP2CYRKYZ7TIDNLGR5QPZ4Q,AGPGDCCXPI3EACMNJKBCNT57DVFA,AFPBMRYRSMD3PP3CBKLFF7EKOCXA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE2JTMRKTUOIVIZWS2WDGTMNTU4Q,AF4QXCB32VC2DVE7O3DGFNQVFFNQ,AGAFYHMPFGVPR3MOS4QAZLAWPW3A,AGNNWLEF6V57TKIFJM7SWHNFAIQQ,AFVIPOPKMOCVCX3CMXUJHMWDIMGA,AH6MFUU725GG4KA3XTALSTU2ILHA,AGQYTSKE2UBYARZYRBADQMX6BJPQ,AG7F66F724JZ2HIJQY7NOU5M5D2Q",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE2OFVZSIE6KSBAPG6GMKCER35LA,AFEOAY5PB4XEYIOL6DY5WJBOYSKQ,AEJTETVJ7NY3GMARSTJNPOG3AY3A,AFMQHAPYUAV7ZSPABOAVTNZVESWA,AEGYHN3DWMVH2RZLTP2H2A2U6EHA,AFIWP2JBBUU6SH3MK355UEG4TZGA,AF7XGOMQWMA2ITB72BPIVHL23EJA,AHBTDCFI4HA6ONMJZRTYUXAEP46A",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE2QS54KQW357EMHTCIX34UBB2TA,AFGABX3WXI4C644LQXZZG4Z7NYKA,AE6DLJW3TAZT627XBMBJGGCWYBPA,AFNKLWWSK4BYFNHQNBGNO7QDZXUA,AGC5MKCR2T6INKQSLXKV3QQW2KDA,AEZVK7KOH6QDSNG6ZX6VKI3AC4VQ,AEPTTSPMISL3YSYYY4T2U2DI4ICA,AGD63SACQVHFRKSUCH5VYUZSJEBA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE2TSJXRS5BXE6X7WFS7HOFJKCOQ,AEQTFT2S7RDVYEGOX5RBADQ4VY2Q,AHPCHA3K3ZQDEKCNSZJ56BD4HY2A,AH75O6CQEPN6J3Q6VH4WIVD4HZUA,AHNK4EL2BOSS6WRMONWHNWAF5KRA,AERG3U7VI5YCANZA73XOR6KT2SZA,AHAN5RDTJMGOCIYJZKWO2SJFOB3Q,AGHS26EBVZK3HDJBO26J7C5HYCSQ",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE2XBDOYDMXVHS6NWFKR363SXNEQ,AFEWNQ3WHCXFV334RKDY6TQV5F2A,AFYHSM4NZORPAYX4P6XIV3OPZE7Q,AGGJTBH2YKIJVXXHKKLZGI7BDCMA,AGZQ2GV6RFFSGSEEGZCEA55XSYKQ,AF6RMANVDWWGUPHGAQGEI523WDTA,AHUDYFZ2QJF2XQNTH6OYYHJIDGHA,AEOJR4XRHE3AQOTMVVOIESTP34IQ",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"AE2XMB6CEF4SCPYQI75GHNYEAXIA,AGGZZQ5IGA5QAIGYO5NZ6PVT3D7Q,AE6DVWUAWPSVBSLLUQYNPPSQQAJA,AGY5QPHPBISAP2NWFXQM6IUE2FSA,AGFVUN4637QP6LIOV5R4RLQWPRAQ,AGFVDEDXE3HZWF4WGRUEPMDEGISA,AGLQGHCAPA45C7LFUS257GLOBJIQ,AHHZDQ4MJ63XTHK5UTCXGFSPQNTA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
user_item_filled = user_item_matrix.fillna(0)

In [43]:
user_item_filled.iloc[:10, :10]

product_id,B002PD61Y4,B002SZEOLG,B003B00484,B003L62T7W,B004IO5BMQ,B005FYNT3G,B005LJQMCK,B005LJQMZC,B006LW0WDQ,B0073QGKAS
user_id,,,,,,,,,,
"AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZAHJK6NGYHFMA,AGYURQ3476BNT4D2O46THXEUY3SA,AFPMBSBIEX45OQ6UCQWPDG55GWLQ,AGWJU3WUQBDQYPSYAJSR3AKBLCOA,AEOVUNFCIFV223O536GVW5JHZKOA",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE23RS3W7GZO7LHYKJU6KSKVM4MQ,AEQUNEY6GQOTEGUMS6KRUEYNXJSQ,AGYPIE5BICV44WEEEPJVEFQOCJSQ,AFR7CEQKWZE53IHHOWBIPAMYKL4Q,AGBV7FBP4SEITF6UKRFKTV7O32IA,AHQVOY54QKPIQZIJ57JKCGQPVV3Q,AEMCVRRD3XQRGFHC2VFCXHJEMESQ,AFBWXU7DUWCIK5MRDCLBXWTWN7ZQ",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AE242TR3GQ6TYC6W4SJ5UYYKBTYQ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE27UOZENYSWCQVQRRUQIV2ZM7VA,AGMYSLV6NNOAYES25JDTJPCZY47A,AFHS33MWRQGSS64EETZJGCBWXXXA,AHYXZVXUY3QTBP7IBFIUBSZVH2XQ,AH2SHWYEWDAK6A5Y2ZBEMZ2KIG3A,AEYMOGP2CYRKYZ7TIDNLGR5QPZ4Q,AGPGDCCXPI3EACMNJKBCNT57DVFA,AFPBMRYRSMD3PP3CBKLFF7EKOCXA",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE2JTMRKTUOIVIZWS2WDGTMNTU4Q,AF4QXCB32VC2DVE7O3DGFNQVFFNQ,AGAFYHMPFGVPR3MOS4QAZLAWPW3A,AGNNWLEF6V57TKIFJM7SWHNFAIQQ,AFVIPOPKMOCVCX3CMXUJHMWDIMGA,AH6MFUU725GG4KA3XTALSTU2ILHA,AGQYTSKE2UBYARZYRBADQMX6BJPQ,AG7F66F724JZ2HIJQY7NOU5M5D2Q",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE2OFVZSIE6KSBAPG6GMKCER35LA,AFEOAY5PB4XEYIOL6DY5WJBOYSKQ,AEJTETVJ7NY3GMARSTJNPOG3AY3A,AFMQHAPYUAV7ZSPABOAVTNZVESWA,AEGYHN3DWMVH2RZLTP2H2A2U6EHA,AFIWP2JBBUU6SH3MK355UEG4TZGA,AF7XGOMQWMA2ITB72BPIVHL23EJA,AHBTDCFI4HA6ONMJZRTYUXAEP46A",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE2QS54KQW357EMHTCIX34UBB2TA,AFGABX3WXI4C644LQXZZG4Z7NYKA,AE6DLJW3TAZT627XBMBJGGCWYBPA,AFNKLWWSK4BYFNHQNBGNO7QDZXUA,AGC5MKCR2T6INKQSLXKV3QQW2KDA,AEZVK7KOH6QDSNG6ZX6VKI3AC4VQ,AEPTTSPMISL3YSYYY4T2U2DI4ICA,AGD63SACQVHFRKSUCH5VYUZSJEBA",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE2TSJXRS5BXE6X7WFS7HOFJKCOQ,AEQTFT2S7RDVYEGOX5RBADQ4VY2Q,AHPCHA3K3ZQDEKCNSZJ56BD4HY2A,AH75O6CQEPN6J3Q6VH4WIVD4HZUA,AHNK4EL2BOSS6WRMONWHNWAF5KRA,AERG3U7VI5YCANZA73XOR6KT2SZA,AHAN5RDTJMGOCIYJZKWO2SJFOB3Q,AGHS26EBVZK3HDJBO26J7C5HYCSQ",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE2XBDOYDMXVHS6NWFKR363SXNEQ,AFEWNQ3WHCXFV334RKDY6TQV5F2A,AFYHSM4NZORPAYX4P6XIV3OPZE7Q,AGGJTBH2YKIJVXXHKKLZGI7BDCMA,AGZQ2GV6RFFSGSEEGZCEA55XSYKQ,AF6RMANVDWWGUPHGAQGEI523WDTA,AHUDYFZ2QJF2XQNTH6OYYHJIDGHA,AEOJR4XRHE3AQOTMVVOIESTP34IQ",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE2XMB6CEF4SCPYQI75GHNYEAXIA,AGGZZQ5IGA5QAIGYO5NZ6PVT3D7Q,AE6DVWUAWPSVBSLLUQYNPPSQQAJA,AGY5QPHPBISAP2NWFXQM6IUE2FSA,AGFVUN4637QP6LIOV5R4RLQWPRAQ,AGFVDEDXE3HZWF4WGRUEPMDEGISA,AGLQGHCAPA45C7LFUS257GLOBJIQ,AHHZDQ4MJ63XTHK5UTCXGFSPQNTA",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
user_similarity = cosine_similarity(user_item_filled)

In [46]:
user_similarity.shape

(1191, 1191)

In [47]:
user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_item_filled.index,
    columns=user_item_filled.index
)

In [48]:
user_similarity_df.head()

user_id,"AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZAHJK6NGYHFMA,AGYURQ3476BNT4D2O46THXEUY3SA,AFPMBSBIEX45OQ6UCQWPDG55GWLQ,AGWJU3WUQBDQYPSYAJSR3AKBLCOA,AEOVUNFCIFV223O536GVW5JHZKOA","AE23RS3W7GZO7LHYKJU6KSKVM4MQ,AEQUNEY6GQOTEGUMS6KRUEYNXJSQ,AGYPIE5BICV44WEEEPJVEFQOCJSQ,AFR7CEQKWZE53IHHOWBIPAMYKL4Q,AGBV7FBP4SEITF6UKRFKTV7O32IA,AHQVOY54QKPIQZIJ57JKCGQPVV3Q,AEMCVRRD3XQRGFHC2VFCXHJEMESQ,AFBWXU7DUWCIK5MRDCLBXWTWN7ZQ",AE242TR3GQ6TYC6W4SJ5UYYKBTYQ,"AE27UOZENYSWCQVQRRUQIV2ZM7VA,AGMYSLV6NNOAYES25JDTJPCZY47A,AFHS33MWRQGSS64EETZJGCBWXXXA,AHYXZVXUY3QTBP7IBFIUBSZVH2XQ,AH2SHWYEWDAK6A5Y2ZBEMZ2KIG3A,AEYMOGP2CYRKYZ7TIDNLGR5QPZ4Q,AGPGDCCXPI3EACMNJKBCNT57DVFA,AFPBMRYRSMD3PP3CBKLFF7EKOCXA","AE2JTMRKTUOIVIZWS2WDGTMNTU4Q,AF4QXCB32VC2DVE7O3DGFNQVFFNQ,AGAFYHMPFGVPR3MOS4QAZLAWPW3A,AGNNWLEF6V57TKIFJM7SWHNFAIQQ,AFVIPOPKMOCVCX3CMXUJHMWDIMGA,AH6MFUU725GG4KA3XTALSTU2ILHA,AGQYTSKE2UBYARZYRBADQMX6BJPQ,AG7F66F724JZ2HIJQY7NOU5M5D2Q","AE2OFVZSIE6KSBAPG6GMKCER35LA,AFEOAY5PB4XEYIOL6DY5WJBOYSKQ,AEJTETVJ7NY3GMARSTJNPOG3AY3A,AFMQHAPYUAV7ZSPABOAVTNZVESWA,AEGYHN3DWMVH2RZLTP2H2A2U6EHA,AFIWP2JBBUU6SH3MK355UEG4TZGA,AF7XGOMQWMA2ITB72BPIVHL23EJA,AHBTDCFI4HA6ONMJZRTYUXAEP46A","AE2QS54KQW357EMHTCIX34UBB2TA,AFGABX3WXI4C644LQXZZG4Z7NYKA,AE6DLJW3TAZT627XBMBJGGCWYBPA,AFNKLWWSK4BYFNHQNBGNO7QDZXUA,AGC5MKCR2T6INKQSLXKV3QQW2KDA,AEZVK7KOH6QDSNG6ZX6VKI3AC4VQ,AEPTTSPMISL3YSYYY4T2U2DI4ICA,AGD63SACQVHFRKSUCH5VYUZSJEBA","AE2TSJXRS5BXE6X7WFS7HOFJKCOQ,AEQTFT2S7RDVYEGOX5RBADQ4VY2Q,AHPCHA3K3ZQDEKCNSZJ56BD4HY2A,AH75O6CQEPN6J3Q6VH4WIVD4HZUA,AHNK4EL2BOSS6WRMONWHNWAF5KRA,AERG3U7VI5YCANZA73XOR6KT2SZA,AHAN5RDTJMGOCIYJZKWO2SJFOB3Q,AGHS26EBVZK3HDJBO26J7C5HYCSQ","AE2XBDOYDMXVHS6NWFKR363SXNEQ,AFEWNQ3WHCXFV334RKDY6TQV5F2A,AFYHSM4NZORPAYX4P6XIV3OPZE7Q,AGGJTBH2YKIJVXXHKKLZGI7BDCMA,AGZQ2GV6RFFSGSEEGZCEA55XSYKQ,AF6RMANVDWWGUPHGAQGEI523WDTA,AHUDYFZ2QJF2XQNTH6OYYHJIDGHA,AEOJR4XRHE3AQOTMVVOIESTP34IQ","AE2XMB6CEF4SCPYQI75GHNYEAXIA,AGGZZQ5IGA5QAIGYO5NZ6PVT3D7Q,AE6DVWUAWPSVBSLLUQYNPPSQQAJA,AGY5QPHPBISAP2NWFXQM6IUE2FSA,AGFVUN4637QP6LIOV5R4RLQWPRAQ,AGFVDEDXE3HZWF4WGRUEPMDEGISA,AGLQGHCAPA45C7LFUS257GLOBJIQ,AHHZDQ4MJ63XTHK5UTCXGFSPQNTA",...,"AHYDKTW3WJO4HNGBHBOAFCJ3LOSA,AE3EGXXGRBM43FWMTLQB37JMC7OQ,AGIHOZJO4PWX5Z37R4I4RQXIZWRA,AE3CC3KBP4BWJZJMRJD4W6DYTXUA,AGMKONPE5QC455TBAZN4QNR73KXQ,AFH3GSHTIVQMKDP27TOCVV33JPOA,AED36GWWMN3IDN6MHKBLYHYCTTYQ,AHOIB4NI2LLE52QK6Y3ISJQUH2RA","AHYKYPQWG6D57RWV5BGGMKG6D6WA,AG4HU2P24AVEA5DIVDDZPAZJB2EA,AEZYF4ZZU6FH47ONFQ4ABO7TAYAQ,AGG2W3XKE7XHPKKOO653RQ2GKYSA,AGCSGQTOFGYS47AB64E7HYCVXPSQ,AE64ROQOZG3YQPANW75Z4DGEOEYQ,AFWJRG3J53U4MB2UJKQBXEU2KLDQ,AEVZ5IEWI4C37B6QZBJEL5H3BRIQ","AHYXJP46LXOTLZ5FXX53OWHFNWXA,AGJH265WIJJRU5CH6R2T3KPDUHUA,AGURQUXEVAYTPSF26X64GZTYMTVA,AEDNDNSMKKRKDTTX67VVJMEQEPPA,AGCUQVPEVBIWQQBLSEKK2LSICLPA,AE3FZBDL2DKG5S23STYXDBEFCLFQ,AHSDXCJVYDH2MU3PQR7TRI5TA4LA,AETU3IBTWBZE4PUKESCCMCBU7FLA","AHYXOMUJUKZHBWHP43ZAB265EDGA,AG4C27NTZZ7HTG6W3ADZYHAUEZCA,AFYACVFEH3NFVZ5LGOPEBKBCLSSQ,AHTHUJC6TX2WAQ5SO24MVWJONMEQ,AHIJ2RAFZZHMUPJJKYHE2CU7ZNEQ,AENGHEFJVZDD5IE57TJ62DY7CY2A,AHOKBMECKUGAAX2ERFRKMQZNSR4Q,AE4PHOB4VRRT6W2L4E5TT4QROAWA","AHYZC7TAK75CSXYF2V57TT2XB3VA,AHVSVASRHLY4HII4CH5GEKNUWAIQ,AHU3G6JL2C765DSFVXYNANCGFATA,AEF7R2XPRQEBGHMMUTQRQNQ7CHLQ,AHMWV64SEF7KPL6YJUVNNIAIEHJA,AHBVHPQ4W6276E6FKYIQHJQ4BMRQ,AH6ZGBUYPQH5WWPNBBMYQMYOOYTA,AH4XKLZAXDJGMB74RNSTAQD6T33Q","AHZFKWGDBRQKNMNQ4ZPL52OZBRKA,AGBEFVJFOQIRF7C7KY5VN6XO7JEA,AGN47LODJXDWX6WWSS5JJLKP2HWQ,AGJRVBQJIVB445HIWTFCZOI37IQA,AHCNUZM2XGWJXQHPWYVZMS5CAEMA,AFQICBBGIA6ED2FXXYEVEVKDFOWQ,AELILYZUYXGJOFN2P7KT7OEUBM2Q,AEJHZ5W2C7AYFISGPX7WSDVSIYEQ","AHZJHJWFZLYD64GVP4PXVI2F4LXA,AEUCRZPOISXKHXMCZUH6BXTUXUWA,AFL2ICS3EEESPGYLFF7OTVYMLVJA,AG63J3CFIT6RYX32RHHYWRZ2WKKA,AE6EGCFBVJIZEZ4XPPIY3PES2SDQ,AHUZG5YJCM4UWL66ALQ744FD3OOA,AEIKB2XA64MPG7BBXRG4DT57QKPQ,AF4ECPZRARF7SK2GDSBPTINVA2CA","AHZNSNBVKQR4OGJAQHE4DCDA4YHA,AFBW6COTZXGHQMWVDUOSXVUCCIHQ,AFFRU7QVLXG4LNG6JKQKJ23KBA2A,AF5E74KNXXYBJVMG7HUYXNRNYY3A,AF4F4SKVD2UU7ZBJFZNNBK7ORIGA,AF3IVRFFILSUOKAXKRZBFBDRF7MQ,AF23WB7B2XKLYCA3KXEGKSBWYKOA,AHAJNAQDV3BHN5AYLY3LOWFJCS6A","AHZWJCVEIEI76H2VGMUSN5D735IQ,AH2DFUHFTG4CKQFVGZSB4JHXSAWA,AGYTSAUTXMOPROERNJPXNEB2XWNQ,AF5JWNCDVWTXOFCICR6IYNOEQENQ,AEEFM3W6RGC2KDYG5B6N7VQXR4QA,AGRT55DXEGF2EOL63HOKKKBB2KFA,AF6R7AMFHIWTMNFF6WPGFDOF7Z5A,AEGXNM3XGAHJGUJ7MIFPE7QFMJHA","AHZWXUWE3RGLDH4JJUK3HT3VMBJA,AFWUWJMEO4IQEMHKMUXYUILK47LQ,AHESBMCCD2JGQWVMDSW2G6QVJS7Q,AGJ2JB67X6WE4WZMZH4NWXHEGP4A,AEH5FAS6HXOZKYQOUM2YV5KKCNHQ,AGZYICOVCDNGVWXHJCDF63UTU7FA,AFIAREIU3BQVJUNZTYKC5I4TTN7A,AGVOPDVJX5H5BXDGMWPRSWAJSJAQ"
user_id,,,,,,,,,,,,,,,,,,,,,
"AE22Y3KIS7SE6LI3HE2VS6WWPU4Q,AHWEYO2IJ5I5GDWZAHJK6NGYHFMA,AGYURQ3476BNT4D2O46THXEUY3SA,AFPMBSBIEX45OQ6UCQWPDG55GWLQ,AGWJU3WUQBDQYPSYAJSR3AKBLCOA,AEOVUNFCIFV223O536GVW5JHZKOA",1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE23RS3W7GZO7LHYKJU6KSKVM4MQ,AEQUNEY6GQOTEGUMS6KRUEYNXJSQ,AGYPIE5BICV44WEEEPJVEFQOCJSQ,AFR7CEQKWZE53IHHOWBIPAMYKL4Q,AGBV7FBP4SEITF6UKRFKTV7O32IA,AHQVOY54QKPIQZIJ57JKCGQPVV3Q,AEMCVRRD3XQRGFHC2VFCXHJEMESQ,AFBWXU7DUWCIK5MRDCLBXWTWN7ZQ",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AE242TR3GQ6TYC6W4SJ5UYYKBTYQ,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE27UOZENYSWCQVQRRUQIV2ZM7VA,AGMYSLV6NNOAYES25JDTJPCZY47A,AFHS33MWRQGSS64EETZJGCBWXXXA,AHYXZVXUY3QTBP7IBFIUBSZVH2XQ,AH2SHWYEWDAK6A5Y2ZBEMZ2KIG3A,AEYMOGP2CYRKYZ7TIDNLGR5QPZ4Q,AGPGDCCXPI3EACMNJKBCNT57DVFA,AFPBMRYRSMD3PP3CBKLFF7EKOCXA",0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"AE2JTMRKTUOIVIZWS2WDGTMNTU4Q,AF4QXCB32VC2DVE7O3DGFNQVFFNQ,AGAFYHMPFGVPR3MOS4QAZLAWPW3A,AGNNWLEF6V57TKIFJM7SWHNFAIQQ,AFVIPOPKMOCVCX3CMXUJHMWDIMGA,AH6MFUU725GG4KA3XTALSTU2ILHA,AGQYTSKE2UBYARZYRBADQMX6BJPQ,AG7F66F724JZ2HIJQY7NOU5M5D2Q",0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [49]:
def recommend_collaborative(user_id, top_n=5):
    similar_users = user_similarity_df[user_id].sort_values(ascending=False)[1:top_n+1]

    similar_users_products = user_item_filled.loc[similar_users.index]

    recommended_products = similar_users_products.mean().sort_values(ascending=False)

    return recommended_products.head(top_n)

In [50]:
recommend_collaborative(df['user_id'].iloc[0])

product_id
B0BJ6P3LSK    0.90
B07YTNKVJQ    0.86
B08DDRGWTJ    0.86
B008LN8KDM    0.86
B0B2PQL5N3    0.84
dtype: float64

In [51]:
df[df['product_id'].isin(recommend_collaborative(df['user_id'].iloc[0]).index)][['product_id','product_name']].drop_duplicates()

      product_id                                       product_name
7     B08DDRGWTJ             MI Usb Type-C Cable Smartphone (Black)
153   B07YTNKVJQ  MI Xiaomi USB Type C HYperCharge Cable 6A 100c...
786   B0B2PQL5N3  Lapster Gel Mouse pad with Wrist Rest , Gaming...
1207  B008LN8KDM  Philips GC1920/28 1440-Watt Non-Stick Soleplat...
1416  B0BJ6P3LSK  Aqua d pure Active Copper 12-L RO+UV Water Fil...

## Collaborative Filtering

In this section, we implemented the **Collaborative Filtering Recommendation System**.  
Unlike content-based filtering, collaborative filtering recommends products based on the behavior and preferences of **similar users**.

### Steps performed:
1. Created a **User-Item Matrix** using `user_id`, `product_id`, and `rating`.
2. Filled missing values (`NaN`) with `0` to represent no interaction.
3. Applied **Cosine Similarity** to measure similarity between users.
4. Built a recommendation function to:
   - Find the most similar users.
   - Collect their highly rated products.
   - Recommend top products to the selected user.

### Observation:
The dataset was highly sparse, meaning most users rated only a small number of products.  
Because of this, user-user similarity was often low.

### Result:
The system successfully generated recommendations based on similar user behavior.  
However, due to sparse interactions, collaborative filtering may be less effective than content-based filtering for this dataset.

This limitation is common in real-world recommendation systems and is known as the **sparsity problem**.

In [52]:
def hybrid_recommend(product_name, user_id, top_n=5):

    content_recs = recommend_products(product_name, top_n).tolist()

    collaborative_recs = recommend_collaborative(user_id, top_n).index.tolist()

    collaborative_names = df[df['product_id'].isin(collaborative_recs)]['product_name'].drop_duplicates().tolist()

    final_recommendations = list(dict.fromkeys(content_recs + collaborative_names))

    return final_recommendations[:top_n]

In [53]:
hybrid_recommend(
    df['product_name'].iloc[123],
    df['user_id'].iloc[0]
)

['Hisense 126 cm (50 inches) Bezelless Series 4K Ultra HD Smart LED Google TV 50A6H (Black)',
 'TCL 108 cm (43 inches) 4K Ultra HD Certified Android Smart LED TV 43P615 (Black)',
 'TCL 100 cm (40 inches) Full HD Certified Android R Smart LED TV 40S6505 (Black)',
 'Samsung 108 cm (43 inches) Crystal 4K Neo Series Ultra HD Smart LED TV UA43AUE65AKXXL (Black)',
 'Toshiba 108 cm (43 inches) V Series Full HD Smart Android LED TV 43V35KP (Silver)']

## Hybrid Recommendation System

In this section, we implemented the **Hybrid Recommendation System** by combining both Content-Based Filtering and Collaborative Filtering.

Hybrid recommendation takes advantage of:
- **Content-Based Filtering** for personalized recommendations based on product features.
- **Collaborative Filtering** for discovery of products based on similar user behavior.

### Steps performed:
1. Generated content-based recommendations using product features such as product name, category, and description.
2. Generated collaborative recommendations using user-product-rating interactions.
3. Converted collaborative product IDs into product names.
4. Combined both recommendation lists.
5. Removed duplicate recommendations.

### Observation:
The hybrid model provided a better balance between personalization and discovery.

### Result:
Hybrid filtering produced more balanced and practical recommendations by reducing the limitations of both individual systems.

## Comparison of Recommendation Systems

| Recommendation System | Strengths | Weaknesses |
|---|---|---|
| Content-Based Filtering | Personalized, fast, uses product features | Can become repetitive |
| Collaborative Filtering | Helps discover new products, uses crowd behavior | Suffers from sparse data problem |
| Hybrid Filtering | Combines personalization and discovery, more balanced | Slightly more complex |

### Dataset Observation:
The Amazon dataset used in this project was highly sparse, meaning users interacted with very few products.  
Because of this, Content-Based Filtering performed better than Collaborative Filtering.

Hybrid Filtering gave the most balanced result overall.

## Conclusion

In this project, we implemented and compared three recommendation systems: Content-Based Filtering, Collaborative Filtering, and Hybrid Filtering.

The Content-Based model performed well because product information such as name, category, and description was rich and useful for similarity matching.

The Collaborative model worked successfully but was limited by the sparse user-product interaction data.

The Hybrid model provided the best overall performance by combining both approaches, improving both personalization and product discovery.

This project shows that Hybrid Recommendation Systems are often the most effective in real-world e-commerce platforms like Amazon.